### ISSUE TITLE
AssetObject被lock可能导致bug

### ISSUE THREAD

**Issue by Lichun-HZ** [EllanJiang/GameFramework#20]
虽然没有用到lock，但在处理时发现这个地方可能导致bug，需Ellan确认。

AssetObject在OnUnspawn()的时候会将其依赖资源全Unspawn，如果在资源层次上把某个AssetObject Lock了，它不会被Release掉，但依赖资源可能会被Release掉。下次加载该资源时就可能出现问题。

解决方法是AssetObject在Lock时，将其依赖资源也lock掉。

好吧，其实你没有开放接口可以对某个资源进行lock，不过说不准谁会自己加一个这样的接口。所以这算一个不是bug的bug。

**Comment by EllanJiang** [comment]
在3.1.3版本中已经修复这个问题，当一个资源被其它资源依赖时，即使引用计数为0，也不会被释放。
