### ISSUE TITLE
事件派发与释放机制

### ISSUE THREAD

**Issue by itachijames** [EllanJiang/GameFramework#31]
事件的释放机制逻辑似乎有些问题（3.1.7）
从应用池里获一个事件`var eventArg = ReferencePool.Acquire<TestEventArgs>()` 然后抛出`GameEntry.Event.Fire(this, eventArg )`，这两行代码似乎必须得绑定执行——如果在`TestEventArgs`里定义了一个其他参数`object TestParam`，每次给参数`TestParam`赋不同值，将`eventArg`作为一个全局变量，每次抛出时就会异常。
也就是说Acquire出来的对象不能重复使用、作为全局变量，Fire后就Release了。不知道这算不算是合理还是就是这么设计的

**Comment by EllanJiang** [comment]
就是这样设计的，为了降低内存分配，
Fire之后，EventArgs将在下次Update之后回收，也就是说，如果想继续访问里面的数据，必须在事件响应函数里自行存储。
