### ISSUE TITLE
UI界面回收问题

### ISSUE THREAD

**Issue by itachijames** [EllanJiang/GameFramework#34]
UIForm类的回收函数OnRecycle里将序列号设成0，是否应设成-1才对？
出现此问题是因为程序里有个地方短时间Close一个UI两次，第一次关闭后序列号置0后，第二次关闭时就会把程序第一个打开的UI（序列号为0，但并非真正我要关的ui）给关了。

**Comment by EllanJiang** [comment]
此问题已修复，SerialId将从1开始。

**Comment by EllanJiang** [comment]
Tag v2019.10.13
