### ISSUE TITLE
SendHeartBeat or !SendHeartBeat

### ISSUE THREAD

**Issue by alexddhuang** [EllanJiang/GameFramework#42]
https://github.com/EllanJiang/GameFramework/blob/0416f39fde69b0f14ec12df2c6b6ad3207612f11/GameFramework/Network/NetworkManager.NetworkChannel.cs#L259

Do I misunderstand this code? I think that this condition should be replaced by

```c#
 if (sendHeartBeat && !m_NetworkChannelHelper.SendHeartBeat()) 
```

After I have successfully sent a heartbeat, it shouldn't report missing a heartbeat.

**Comment by alexddhuang** [comment]
Could you please actively resolve questions from users? Thanks. @EllanJiang

**Comment by EllanJiang** [comment]
The counter will increment when a heart beat is sent successfully rather than the opposite. When the response from server is received, the counter will reset. So when the sending counter exceeds some number, it means the we keeps failing to receive server responses.
