### ISSUE TITLE
加入表格编辑的拓展

### ISSUE THREAD

**Issue by bloodenjoy** [EllanJiang/GameFramework#46]
会考虑加入在unity中对表格进行编辑的功能么， 创建表 编辑表结构和内容  对其他表的引用

**Comment by Shaun-Fong** [comment]
或许你可以试试我[这个](https://github.com/qtghost/DataTableEditor)？

**Comment by EllanJiang** [comment]
暂时不考虑在Unity中编辑，实际效率并不高，不好实现Excel一些拖拽刷数据的功能
