### ISSUE TITLE
unity 5.6.1p4 中 UnityWebRequestAgentHelper 文件报错，编译不通过

### ISSUE THREAD

**Issue by trlanfeng** [EllanJiang/GameFramework#6]
项目编译会报错：
Assets/GameFramework/Scripts/Runtime/WebRequest/UnityWebRequestAgentHelper.cs(100,69): error CS0104: `Utility' is an ambiguous reference between `GameFramework.Utility' and `UnityEngine.Networking.Utility'

**Comment by crazyshader** [comment]
这里和Unity的歧义了，Utility前面加上GameFramework名字空间就好了
